### ISSUE TITLE
Add support for Spring Boot applications

### ISSUE THREAD

**Issue by minherz** [googleapis/java-logging-servlet-initializer#301]
**Is your feature request related to a problem? Please describe.**
The auto-initialization mechanism does not work when used with Spring Boot applications.
The testing environment was Java 11 JDK and Spring Boot:
```yaml
<parent>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-parent</artifactId>
  <version>2.7.7</version>
</parent>
```
The application was composed using https://start.spring.io/

**Describe the solution you'd like**
Similar to how the package works with Jakarta servlets, Jetty, Tomcat and Undertow web servers, it should work with Spring Boot applications.

**Additional context**
It looks like the implementation of the hooking to the Java servlet pipeline does not work with Spring Boot applications.

**Comment by losalex** [comment]
There are no plans to maintain this library going forward - closing this issue, please let me know if you have any comments or concerns
